spring:
  application:
    name: customers
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints.web.exposure.include: health,info,loggers   # so you can tweak at runtime


logging:
  level:
    org.springframework.cloud.client.discovery: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.apache.hc.client5.http.impl.classic: DEBUG
    org.apache.hc.client5.http.wire: DEBUG
    org.apache.hc.core5.http.impl.io: DEBUG
    org.apache.hc.core5.reactor: DEBUG
