server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 15s
      routes:
        - id: customers
          uri: lb://customers         # via Eureka/LoadBalancer
          predicates:
            - Path=/customers/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true
